FROM golang:1.25-alpine3.22

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY internal/ internal/
COPY main.go .

RUN GOOS="linux" GOARCH="amd64" go build -o puff_amd64
RUN GOOS="linux" GOARCH="arm64" go build -o puff_arm64

CMD ["cp", "puff_arm64", "puff_amd64", "/output"]
