FROM alpine:3.22
LABEL authors="lukaszfiszer"

ARG TARGETARCH
ARG PUFF_CURRENT_VERSION
ENV PUFF_CURRENT_VERSION=$PUFF_CURRENT_VERSION

RUN apk add --no-cache tzdata

WORKDIR /app

COPY puff-linux-$TARGETARCH puff

ENTRYPOINT ["./puff"]
