name: CI

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target-arch: [ 'arm64', 'amd64' ]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

    # build
      - name: Setup Go v1.25
        uses: actions/setup-go@v5
        with:
          go-version: 1.25

      - name: Build for linux/${{ matrix.target-arch }}
        run: GOOS=linux GOARCH=${{ matrix.target-arch }} go build -o puff_${{ matrix.target-arch }} main/*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output-${{ matrix.target-arch }}
          path: puff_${{ matrix.target-arch }}

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Dockerfile
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            Dockerfile
          sparse-checkout-cone-mode: false

      - name: Download build amd64
        uses: actions/download-artifact@v4
        with:
          name: build-output-amd64

      - name: Download build arm64
        uses: actions/download-artifact@v4
        with:
          name: build-output-arm64

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag
        id: get_version
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "VERSION=$TAG" >> $GITHUB_OUTPUT
          SHORT_VERSION=$(echo $TAG | cut -d '.' -f 1,2)
          echo "SHORT_VERSION=$SHORT_VERSION" >> $GITHUB_OUTPUT

      # only rc tags
      - name: Build and push (linux/amd64,linux/arm64)
        if: contains(github.event.release.tag_name, '-RC')
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/lukfisz/puff:${{ steps.get_version.outputs.VERSION }}

      # only release tags
      - name: Build and push (linux/amd64,linux/arm64)
        if: ${{ !contains(github.event.release.tag_name, '-RC') }}
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/lukfisz/puff:latest
            ghcr.io/lukfisz/puff:${{ steps.get_version.outputs.SHORT_VERSION }}
            ghcr.io/lukfisz/puff:${{ steps.get_version.outputs.VERSION }}