name: CI

on:
  pull_request:
    types:
      - synchronize
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: get_version
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "VERSION=$TAG" >> $GITHUB_OUTPUT
          SHORT_VERSION=$(echo $TAG | cut -d '.' -f 1,2)
          echo "SHORT_VERSION=$SHORT_VERSION" >> $GITHUB_OUTPUT
          if [[ "$TAG" == *"rc"* ]] || [[ "$TAG" == *"RC"* ]]; then
            echo "IS_RC=true" >> $GITHUB_OUTPUT
          else
            echo "IS_RC=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build puff-builder image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          file: Dockerfile-builder
          tags: puff-builder

      - name: Copy compiled app from puff-builder
        run: |
          docker run --rm \
          -v ${{ github.workspace }}:/github/workspace \
          puff-builder

      - name: Build and push Docker image (for RC tags)
        if: steps.get_version.outputs.IS_RC == 'true'
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: |
            PUFF_CURRENT_VERSION=${{ steps.get_version.outputs.VERSION }}
          push: false
          tags: ghcr.io/lukfisz/puff:${{ steps.get_version.outputs.VERSION }}

      - name: Build and push Docker image
        if: steps.get_version.outputs.IS_RC == 'false'
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: |
            PUFF_CURRENT_VERSION=${{ steps.get_version.outputs.VERSION }}
          push: false
          tags: |
            ghcr.io/lukfisz/puff:latest
            ghcr.io/lukfisz/puff:${{ steps.get_version.outputs.SHORT_VERSION }}
            ghcr.io/lukfisz/puff:${{ steps.get_version.outputs.VERSION }}

#      - name: Create GitHub release
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ steps.get_version.outputs.VERSION }}
#          release_name: Release ${{ steps.get_version.outputs.VERSION }}
#          prerelease: ${{ steps.get_version.outputs.IS_RC }}
#          body: |
#            Release for version ${{ steps.get_version.outputs.VERSION }}